# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI proccess newus.id

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20]
    env: 
      NEXT_PUBLIC_API_URL: https://api-services.newus.id/api
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Run Npm
      run: npm ci
    - name: Build Proccess
      run: npm run build --if-present
    - name : change repo
      run : cd /home/root-newus/htdocs/newus.id/actions-runner/_work/website-fe/website-fe
    
